CREATE DATABASE stac2020;

use stac2020;

create table USER  
(
    ID INT PRIMARY KEY AUTO_INCREMENT, 
    NAME VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL
);

create table RECODE
(
    UID INT NOT NULL, 
    FOREIGN KEY (UID) REFERENCES USER(ID) ON UPDATE CASCADE,
    NUM INT PRIMARY KEY AUTO_INCREMENT, #자동생성
    DATETIME DATETIME NOT NULL DEFAULT NOW(), #날짜 시간 생성
    HASH varCHAR(200) NOT NULL,
    SIZE INT NOT NULL
);

describe user;

describe recode;

SELECT * FROM USER LEFT JOIN RECODE ON USER.ID = RECODE.UID WHERE ID = ;